language: node_js
node_js:
  - 12
addons:
  packages:
    - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache
script:
  - npm run lint
  - npm run test:coveralls
  - npm run test:cypress:ci
deploy:
  provider: heroku
  api_key: $HEROKU_API
  app: fordevs-react
  skip_cleanup: true
notifications:
  email: false